### ISSUE TITLE
[Bug] failed: timeout 5000ms exceeded

### ISSUE THREAD

**Issue by asherism** [social-manager-tools/socialmanagertools-igbot#169] opened 2019-05-18 00:01 UTC
Eventually the bot errors out on a timeout requiring a full restart

```
{ TimeoutError: waiting for selector "main header section ul li:nth-child(2) a" failed: timeout 5000ms exceeded
    at new WaitTask (/app/node_modules/puppeteer/lib/FrameManager.js:955:28)
    at Frame._waitForSelectorOrXPath (/app/node_modules/puppeteer/lib/FrameManager.js:846:12)
    at Frame.waitForSelector (/app/node_modules/puppeteer/lib/FrameManager.js:804:17)
    at Page.waitForSelector (/app/node_modules/puppeteer/lib/Page.js:982:29)
    at Likemode_competitor_users.get_followers (/app/modules/mode/likemode_competitor_users.js:127:19)
    at Likemode_competitor_users.start (/app/modules/mode/likemode_competitor_users.js:229:16)
    at <anonymous> name: 'TimeoutError' }
```

**Comment by ptkdev** [comment] 2019-05-18 00:03
Hi!
Happen only in `likemode_competitor_users` mode?

**Comment by asherism** [comment] 2019-05-18 00:05
yes, it definitely happens in `likemode_competitor_users` but i am not sure about the other modes as i haven't used them

**Comment by Digigreg** [comment] 2019-05-18 08:37
Czesc Patryk.
I can confirm, even in the latest version, the problem exist even in fdf_classic mode on Raspberry pi 3.

I'm trying your bot from 5-6 months, and this issue happened from the begin randomly. Let's say the average of once per two days. If you remember we have already talked about that months ago.

Personally, I think that the "worst problem" of this issue is the mandatory full restart of the bot. It's mean that we should check it every N hours to ensure its correct operation.

Cheers

**Comment by ptkdev** [comment] 2019-05-18 10:43
@Digigreg @asherism i upgraded puppeeter to 1.13, this version work with chrome v74 or later. 

On raspian9 chrome version is v71 or v69 (i not remember). You need downgrade puppeeter, see [docs](https://github.com/social-manager-tools/socialmanagertools-docs/blob/master/en/igbot/installation/raspberry/README.md#6-install-correct-puppeteer-module) 

Other solution is download this [zip](https://github.com/social-manager-tools/socialmanagertools-igbot/releases/download/0.9.16/timeoutfix-modules-raspian9.zip)  and replace your "**modules**" folder with zip modules folder. This fix update timeout from **5sec** to **15sec**.

**Comment by Digigreg** [comment] 2019-05-18 17:20
@ptkdev many thanks for your time.

I've just tryed both the ways, but the problem persist, especially if I try to run more accounts together (3-4 accounts on one Raspberry pi 3 B+).

Raspbian 9 uses Chromium v72.

The problem was present even in the previous version of the bot, not only in the latest release.

**Comment by ptkdev** [comment] 2019-05-18 17:27
@Digigreg 
1) `npm install puppeteer@1.11.0` in bot folder
2) Download **[modules](https://github.com/social-manager-tools/socialmanagertools-igbot/releases/download/0.9.16/timeoutfix-modules-raspian9.zip)** folder and replace in bot folder (in 0.9.1 i changed timeout to 5s,  this patch increases it to: : 15s)

If happen again, **try check witch htop the ram usage**: you probably ran out of RAM (1 account = 1 chrome session: ~300mb of ram)

**Comment by asherism** [comment] 2019-07-04 00:40
unfortunately this is still happening with the latest release. 

i am using the docker image on a raspberry pi.

**Comment by ptkdev** [comment] 2019-07-04 00:43
@asherism These days, instagram servers in Europe are down, it's difficult to test and fix the bugs. For example, today hashtags have "no photos". Stay tuned...

**Comment by asherism** [comment] 2019-07-04 00:53
let me know if i can help out in any way 👍

**Comment by asherism** [comment] 2019-07-04 03:46
downgrading puppeteer to 1.6.2 seems to have fixed the issue


```
docker exec -it my_container bash
npm install puppeteer@1.6.2
```

restart the docker container

**Comment by ptkdev** [comment] 2019-07-04 07:36
@asherism good, i write this in [docs](https://github.com/social-manager-tools/socialmanagertools-docs/blob/master/en/igbot/installation/raspberry/README.md#6-install-correct-puppeteer-module).

**Raspian 9** = chrome `v69`
**Raspian 10** = chrome `v74`

**Comment by asherism** [comment] 2019-07-06 17:53
spoke too soon- error is still happening. going to keep debugging.

**Comment by ptkdev** [comment] 2020-04-25 14:59
Fixed in **latest** release.

**Closed by ptkdev** 2020-04-25 14:59 UTC
Labels: bug, mode like: competitor_users, raspbian
